{% set name = "debussy" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrakitin/DEBUSSY_v2.2-UNIX/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6c8d4a22628c8bb6da923aa85f827f64b7704a4a96cfba483f3d157ccb9c8a53
  patches:
    - 0001-PATCH-remove-interactivity.patch
    - 0002-FIX-use-FC-for-fortran-compiler-var.patch
    - 0003-FIX-make-FC-optional-in-makefiles.patch

build:
  number: 0
  skip: true  # [py<38 or win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf
    - automake
    - cerf
    - libtool
    - make
    - nlopt
  host:
    - python
  run:
    - python
    - cerf
    - matplotlib
    - nlopt
    - wxpython

test:
  requires:
    - git
  commands:
    - test -f ${PREFIX}/bin/Debussy
    - ldd ${PREFIX}/bin/Debussy
    - |
      git clone https://github.com/mrakitin/DEBUSSY_v2.2-UNIX /tmp/debussy-repo && \
      cd /tmp/debussy-repo/UNIX/RUN_TEST_UNIX && \
      echo -e "\n" | bash ./drun

about:
  home: https://github.com/DeByeUSerSYstem/DEBUSSY_v2.2-UNIX
  license: GPL-3.0
  license_file: LICENSE
  summary: |
    Debussy is a package of programs implementing a fast approach to the Debye
    Scattering Equation (DSE) analysis for total scattering data from
    nanocrystalline and/or defective materials.

extra:
  recipe-maintainers:
    - mrakitin
