{% set name = "debussy" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrakitin/DEBUSSY_v2.2-UNIX/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6c8d4a22628c8bb6da923aa85f827f64b7704a4a96cfba483f3d157ccb9c8a53
  patches:
    - 0001-CI-run-the-test-after-building.patch

build:
  number: 0
  skip: true  # [py<38 or win or osx]

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    # - pkg-config
  host:
    - libblas * *openblas
    - liblapack
    - cerf
    - nlopt
    - python
  run:
    - python
    - matplotlib
    - wxpython

test:
  commands:
    - test -f ${PREFIX}/bin/Debussy

about:
  home: https://github.com/DeByeUSerSYstem/DEBUSSY_v2.2-UNIX
  license: GPL-3.0
  license_file: LICENSE
  summary: |
    Debussy is a package of programs implementing a fast approach to the Debye
    Scattering Equation (DSE) analysis for total scattering data from
    nanocrystalline and/or defective materials.

extra:
  recipe-maintainers:
    - mrakitin
